name: halfmarathon-predictor
region: fra

services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: your-username/halfmarathon-predictor
      branch: main
      deploy_on_push: true
    
    http_port: 8501
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    health_check:
      http_path: /_stcore/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    routes:
      - path: /
    
    envs:
      # Digital Ocean Spaces
      - key: DO_SPACES_REGION
        value: fra1
      - key: DO_SPACES_ENDPOINT
        value: https://fra1.digitaloceanspaces.com
      - key: DO_SPACES_BUCKET
        value: halfmarathon-predictor
      - key: DO_SPACES_KEY
        type: SECRET
        scope: RUN_TIME
      - key: DO_SPACES_SECRET
        type: SECRET
        scope: RUN_TIME
      
      # OpenAI
      - key: OPENAI_API_KEY
        type: SECRET
        scope: RUN_TIME
      
      # Langfuse
      - key: LANGFUSE_PUBLIC_KEY
        type: SECRET
        scope: RUN_TIME
      - key: LANGFUSE_SECRET_KEY
        type: SECRET
        scope: RUN_TIME
      - key: LANGFUSE_HOST
        value: https://cloud.langfuse.com
